### ISSUE TITLE
Sethome

### ISSUE THREAD

**Issue by asanaik** [AleGuzAva/EEssentials#34]
I can't seem to find a way to increase the amount of homes someone can set, it just says you have the maximum homes and that number is (0), I couldn't see anything in the config.
![image](https://github.com/user-attachments/assets/d01c5545-3a56-44da-b0b0-d5ffb7479d45)

**Comment by asanaik** [comment]
Also since im here asking, is there a way to make the random teleport only teleport withing world border?

**Comment by asanaik** [comment]
nvm I found it

**Comment by dyban** [comment]
What did you find? And where was it?

**Comment by AleGuzAva** [comment]
Use the permission node:

eessentials.homes.#

and replace # with the amount of homes you want the user/group to have. 

This is found in the Permissions section of the wiki

**Comment by dyban** [comment]
Thank you so dang much!
