### ISSUE TITLE
loading world problem

### ISSUE THREAD

**Issue by vaniron** [AleGuzAva/EEssentials#37]
Hi, i am using [Multiworld](https://modrinth.com/mod/multiworld) mod on my server to load additional worlds.
Problem is that /spawn gives me error below, but its working fine if i use `/eessentials reload` before so I guess its trying to load the world from json before it is actually loaded on startup? Reloding then helps because the world is loaded?

Error:
[https://pastebin.com/raw/NjYPN4MG](https://pastebin.com/raw/NjYPN4MG)

Here is my config Locations.json:
```
{
  "modImports": [],
  "warps": {},
  "spawn": {
    "world": "multiworld:spawn",
    "x": 0.0,
    "y": 69.0,
    "z": 0.0,
    "pitch": -19.2,
    "yaw": 91.0
  }
}
```

Can something be done about it? Or is it multiworld problem?
Its repo: [https://github.com/IsaiahMC/multiworld](https://github.com/IsaiahMC/multiworld)

**Comment by AleGuzAva** [comment]
Hey there, can you provide more information such as the EEssentials/Fabric versions you're running, as well as what the intended spawn dimension is supposed to be?

Posting entire logs will also let me help you out better :)

**Comment by aglarcz** [comment]
EEssentials-2.2.0 on fabric 1.21.1
Full log here: [https://pastebin.com/raw/y0f2fWr0](https://pastebin.com/raw/y0f2fWr0)

Spawn is another world created via that multiworld mod to be entrance lobby for the server.

**Comment by aglarcz** [comment]
Great, thanks.
